### ISSUE TITLE
Doesn't work on Forge 1.20.1

### ISSUE THREAD

**Issue by mpustovoi** [SettingDust/ReputationViewer#5]
The Jade tooltip I don't have reputation tooltip, even after I hit a villager:
![2024-10-03_11 39 09](https://github.com/user-attachments/assets/7ea96eba-17c4-4015-951c-b3a015105caf)
I just tested it on minimal setup:
![image](https://github.com/user-attachments/assets/154f0e4f-3a37-40e3-ba8d-c4edee4ae9c0)
Here are the logs: https://mclo.gs/I7QEqoW.

**Comment by SettingDust** [comment]
Will it work if wthit installed?

**Comment by mpustovoi** [comment]
No, it doesn't work with wthit either:
![2024-10-03_13 54 58](https://github.com/user-attachments/assets/64b0b500-4c23-4562-a0bf-e307c47f0bb0)
Logs: https://mclo.gs/JOcy1F9.
Still, I prefer to use Jade.

**Comment by SettingDust** [comment]
Try the new 0.4.2 for jade. Wthit isn't working with connector on Forge. I have no idea for the reason. It's fine on Fabric.
Jade should work fine

**Comment by mpustovoi** [comment]
0.4.2 works fine with Jade:
![2024-10-03_15 23 40](https://github.com/user-attachments/assets/0f28f2b0-474a-40e7-a9ab-5b133ea9f5c1)
However, the Modrinth App will try to break a custom modpack every time since there's is a Forge v0.1.0 of this mod:
![image](https://github.com/user-attachments/assets/cb4010a9-9589-4287-9f69-af00dfc28816)

**Comment by mpustovoi** [comment]
Since v0.1.0 already requires a Connector in dependencies, can you also mark the v0.4.2 as Forge-compatible in Modrinth?

**Comment by SettingDust** [comment]
Modrinth is avoiding mods mark as the loader that isn't actually platform specified. That's why the later versions not forge

**Comment by SettingDust** [comment]
I removed quilt and forge from 0.1.0

**Comment by mpustovoi** [comment]
Got it.
I suppose Modrinth needs some more time for indexing, since so far it offers me to upgrade from v0.4.2 to v0.1.0.
Anyway, the problem has been solved. Thank you for your work!
